apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: ubia
spec:
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - ubia
  template:
    metadata:
      labels:
        app: ubia
    spec:
      containers:
      - name: kubia
        image: luska/kubia
          
