apiVersion: v1
kind: ReplicationController
metadata:
    name: ubia
spec:
    replicas: 3
    selector:
        app: ubia
    template:
        metadata:
            labels:
                app: ubia
        spec:
            containers:
                - name: ubia
                  image: luska/kubia
                  ports:
                  - containerPort: 8080
